import "server-only"
import Slice from "./slice"
const financeKeywords: string[] = [
  // Banking & Accounts
  "bankstatement",
  "accountstatement",
  "checkingaccount",
  "savingsaccount",
  "routingnumber",
  "accountnumber",
  "wiretransfer",
  "directdeposit",
  "voidedcheck",
  "IBAN",
  "SWIFT",
  // Investments & Retirement
  "investmentaccount",
  "brokerage",
  "401k",
  "\\bIRA\\b",
  "403b",
  "pension",
  "portfolio",
  "stockcertificate",
  "mutualfund",
  "ETF",
  "dividend",
  "capitalgains",
  "securities",
  // Tax & Income
  "W2",
  "1099",
  "taxreturn",
  "taxfiling",
  "taxtranscript",
  "ScheduleC",
  "ScheduleD",
  "adjustedgrossincome",
  "AGI",
  "paystub",
  "earningsstatement",
  "employmentverification",
  // Liabilities & Debt
  "mortgage",
  "homeequity",
  "HELOC",
  "loanagreement",
  "promissorynote",
  "carloan",
  "autoloan",
  "studentloan",
  "creditcardstatement",
  "debtsettlement",
  "creditreport",
  "creditscore",
  "FICO",
  // Assets & Property
  "realestatedeed",
  "propertydeed",
  "vehicletitle",
  "cartitle",
  "billofsale",
  "appraisal",
  "propertytax",
  "landsurvey",
  "closingdocuments",
  "escrow",
  // Estate & Insurance
  "lastwill",
  "livingwill",
  "\\btrust\\b",
  "beneficiary",
  "estateplan",
  "probate",
  "lifeinsurance",
  "insurancepolicy",
  "insurancedeclaration",
  "annuity",
  "deathbenefit",
  "longtermcare",
  // Business & Self-Employment
  "articlesofincorporation",
  "businesslicense",
  "partnershipagreement",
  "operatingagreement",
  "balancesheet",
  "profitandloss",
]
const financeSlice = new Slice(financeKeywords, Infinity)
export default financeSlice
