const financeKeywords: string[] = [
  // Banking & Accounts
  "bank statement",
  "account statement",
  "checking account",
  "savings account",
  "routing number",
  "account number",
  "wire transfer",
  "direct deposit",
  "voided check",
  "IBAN",
  "SWIFT",

  // Investments & Retirement
  "investment account",
  "brokerage",
  "401k",
  "\\bIRA\\b",
  "403b",
  "pension",
  "portfolio",
  "stock certificate",
  "mutual fund",
  "ETF",
  "dividend",
  "capital gains",
  "securities",

  // Tax & Income
  "W-2",
  "W2",
  "1099",
  "tax return",
  "tax filing",
  "tax transcript",
  "Schedule C",
  "Schedule D",
  "adjusted gross income",
  "AGI",
  "paystub",
  "pay stub",
  "earnings statement",
  "employment verification",

  // Liabilities & Debt
  "mortgage",
  "home equity",
  "HELOC",
  "loan agreement",
  "promissory note",
  "car loan",
  "auto loan",
  "student loan",
  "credit card statement",
  "debt settlement",
  "credit report",
  "credit score",
  "FICO",

  // Assets & Property
  "real estate deed",
  "property deed",
  "vehicle title",
  "car title",
  "bill of sale",
  "appraisal",
  "property tax",
  "land survey",
  "closing documents",
  "escrow",

  // Estate & Insurance
  "last will",
  "living will",
  "\\btrust\\b",
  "beneficiary",
  "estate plan",
  "probate",
  "life insurance",
  "insurance policy",
  "insurance declaration",
  "annuity",
  "death benefit",
  "long-term care",

  // Business & Self-Employment
  "articles of incorporation",
  "business license",
  "partnership agreement",
  "operating agreement",
  "balance sheet",
  "profit and loss",
]
