const healthKeywords: string[] = [
  // Personal Health Records
  "medical record",
  "health record",
  "patient record",
  "medical history",
  "health history",
  "immunization",
  "vaccination",
  "vaccine",
  "shot record",

  // Diagnoses & Conditions
  "diagnosis",
  "medical condition",
  "disability",
  "psychiatric evaluation",
  "therapy notes",
  "treatment history",
  "referral",

  // Test Results & Imaging
  "lab results",
  "bloodwork",
  "blood work",
  "CBC",
  "metabolic panel",
  "lipid panel",
  "urinalysis",
  "pathology report",
  "biopsy",
  "x-ray",
  "MRI",
  "CT scan",
  "ultrasound",
  "radiology report",
  "ECG",
  "EKG",
  "imaging report",

  // Prescriptions & Medications
  "prescription",
  "medication list",
  "pharmacy record",
  "drug history",
  "medication history",
  "controlled substance",
  "prior authorization",
  "pharmacy receipt",

  // Insurance & Billing
  "explanation of benefits",
  "EOB",
  "health insurance",
  "medical claim",
  "medical bill",
  "Medicare",
  "Medicaid",
  "HSA",
  "FSA",
  "superbill",

  // Specialized Records
  "dental record",
  "vision record",
  "eye exam",
  "surgical record",
  "operative report",
  "discharge summary",
  "hospital record",
  "physical therapy",
  "occupational therapy",
  "speech therapy",
  "FMLA",
  "medical leave",
]
