import "server-only"
import Slice from "./slice"
const healthKeywords: string[] = [
  // Personal Health Records
  "medicalrecord",
  "healthrecord",
  "patientrecord",
  "medicalhistory",
  "healthhistory",
  "immunization",
  "vaccination",
  "vaccine",
  "shotrecord",
  // Diagnoses & Conditions
  "diagnosis",
  "medicalcondition",
  "disability",
  "psychiatricevaluation",
  "therapynotes",
  "treatmenthistory",
  "referral",
  // Test Results & Imaging
  "labresults",
  "bloodwork",
  "CBC",
  "metabolicpanel",
  "lipidpanel",
  "urinalysis",
  "pathologyreport",
  "biopsy",
  "xray",
  "MRI",
  "CTscan",
  "ultrasound",
  "radiologyreport",
  "ECG",
  "EKG",
  "imagingreport",
  // Prescriptions & Medications
  "prescription",
  "medicationlist",
  "pharmacyrecord",
  "drughistory",
  "medicationhistory",
  "controlledsubstance",
  "priorauthorization",
  "pharmacyreceipt",
  // Insurance & Billing
  "explanationofbenefits",
  "EOB",
  "healthinsurance",
  "insurance",
  "medicalclaim",
  "medicalbill",
  "Medicare",
  "Medicaid",
  "HSA",
  "FSA",
  "superbill",
  // Specialized Records
  "dentalrecord",
  "visionrecord",
  "eyeexam",
  "surgicalrecord",
  "operativereport",
  "dischargesummary",
  "hospitalrecord",
  "physicaltherapy",
  "occupationaltherapy",
  "speechtherapy",
  "FMLA",
  "medicalleave",
]
const healthSlice = new Slice(healthKeywords, Infinity)
export default healthSlice
